exp_name: 'tarot_test'
seed: 42 # random seed
device: 'cuda:0'
selection_ratio: 0.2
selection_method: 'fixed_size' #otm #random
ckpt_dir: './unitraj_ckpt'
ckpt_usage: 1 # will use last n ckpts in the ckpt_dir
projection_dimension: 4096
feature_save_dir: './wfd_results_test'
k_fold_splits: 10 # number of splits for k-fold cross validation of OTM (Refer to the paper for more details)
merge_target_data: True # whether to merge target data with candidate data for training
data_weighting: False # whether to use data weighting for training

